spring.datasource.url=jdbc:postgresql://localhost:5432/hostel_db
spring.datasource.username=Shrutika
spring.datasource.password=Shrutika@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8080